"""form_id column added

Revision ID: 834d97db61e0
Revises: ef5d72b76e00
Create Date: 2021-08-22 23:25:35.846405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '834d97db61e0'
down_revision = 'ef5d72b76e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('form_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'form_id')
    # ### end Alembic commands ###
