"""Create Tasks table

Revision ID: ca01e39f3ebf
Revises: 94bb069a8f6d
Create Date: 2021-08-22 23:17:32.711618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca01e39f3ebf'
down_revision = '94bb069a8f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
