"""Removed FormQuestion

Revision ID: 8a4a79e22a0f
Revises: f93b24f183c2
Create Date: 2021-08-21 04:02:05.222722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a4a79e22a0f'
down_revision = 'f93b24f183c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formQuestions')
    op.add_column('questions', sa.Column('form_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('questions', sa.Column('question_order', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'questions', ['form_id', 'question_order'])
    op.create_foreign_key(None, 'questions', 'forms', ['form_id'], ['id'], ondelete='CASCADE')
    op.add_column('responses', sa.Column('response_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'responses', 'formResponses', ['response_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_column('responses', 'response_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'question_order')
    op.drop_column('questions', 'form_id')
    op.create_table('formQuestions',
    sa.Column('form_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name='formQuestions_form_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='formQuestions_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id', 'question_id', name='formQuestions_pkey'),
    sa.UniqueConstraint('form_id', 'question_order', name='formQuestions_form_id_question_order_key')
    )
    # ### end Alembic commands ###
